version: "3.4"
services:

  mongodb-service:
    image: mongo
    container_name: mongo-ecommerce-wishlist
    networks: 
      - rede-one 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=admin
      
  ecommerce-wishlist-api-service:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: ecommerce-wishlist-api
    networks: 
      - rede-one
    ports:
      - "8080:8080"
    depends_on: 
      - "mongodb-service"
      
networks:
  rede-one:
    driver: bridge